name: deep_pick
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/passsy/deep_pick
author: Pascal Welsch <pascal.welsch@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
